version: '2.2'

services:
  coredns:
    image: coredns/coredns
    container_name: coredns_dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ${PWD}/Corefile:/Corefile
      - /etc/hosts:/etc/hosts
